[project]
name = "itg-buddy-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "grpcio>=1.66.2",
    "itg-cli>=0.1.0",
]

[tool.uv]
dev-dependencies = [
    "grpcio-tools>=1.66.2",
]
