# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: itg_buddy_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'itg_buddy_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17itg_buddy_service.proto\x12\x11itg_buddy_service\"8\n\x0e\x41\x64\x64SongRequest\x12\x13\n\x0bpath_or_url\x18\x01 \x01(\t\x12\x11\n\toverwrite\x18\x02 \x01(\x08\":\n\x0f\x41\x64\x64SongResponse\x12\x12\n\nadded_song\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t2[\n\x07itg_cli\x12P\n\x07\x41\x64\x64Song\x12!.itg_buddy_service.AddSongRequest\x1a\".itg_buddy_service.AddSongResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'itg_buddy_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDSONGREQUEST']._serialized_start=46
  _globals['_ADDSONGREQUEST']._serialized_end=102
  _globals['_ADDSONGRESPONSE']._serialized_start=104
  _globals['_ADDSONGRESPONSE']._serialized_end=162
  _globals['_ITG_CLI']._serialized_start=164
  _globals['_ITG_CLI']._serialized_end=255
# @@protoc_insertion_point(module_scope)
