# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: itg_buddy.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'itg_buddy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fitg_buddy.proto\x12\titg_buddy\"8\n\x0e\x41\x64\x64SongRequest\x12\x13\n\x0bpath_or_url\x18\x01 \x01(\t\x12\x11\n\toverwrite\x18\x02 \x01(\x08\":\n\x0f\x41\x64\x64SongResponse\x12\x12\n\nadded_song\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t2U\n\x11SimfileManagement\x12@\n\x07\x41\x64\x64Song\x12\x19.itg_buddy.AddSongRequest\x1a\x1a.itg_buddy.AddSongResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'itg_buddy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDSONGREQUEST']._serialized_start=30
  _globals['_ADDSONGREQUEST']._serialized_end=86
  _globals['_ADDSONGRESPONSE']._serialized_start=88
  _globals['_ADDSONGRESPONSE']._serialized_end=146
  _globals['_SIMFILEMANAGEMENT']._serialized_start=148
  _globals['_SIMFILEMANAGEMENT']._serialized_end=233
# @@protoc_insertion_point(module_scope)
