# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import itg_buddy_pb2 as itg__buddy__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in itg_buddy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimfileManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddSong = channel.unary_unary(
                '/itg_buddy.SimfileManagement/AddSong',
                request_serializer=itg__buddy__pb2.AddSongRequest.SerializeToString,
                response_deserializer=itg__buddy__pb2.AddSongResponse.FromString,
                _registered_method=True)


class SimfileManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddSong(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimfileManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddSong': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSong,
                    request_deserializer=itg__buddy__pb2.AddSongRequest.FromString,
                    response_serializer=itg__buddy__pb2.AddSongResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'itg_buddy.SimfileManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('itg_buddy.SimfileManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimfileManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddSong(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/itg_buddy.SimfileManagement/AddSong',
            itg__buddy__pb2.AddSongRequest.SerializeToString,
            itg__buddy__pb2.AddSongResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
